# prometheus.yml
global:
  scrape_interval: 5s
  
  external_labels:
    monitor: 'my-monitor'


scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'local'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          group: 'node-exporter'
         
  - job_name: 'exporter'
    static_configs:
      - targets: ['exporter:9104']
        labels:
          group: db1
